### ISSUE TITLE
Problem with shaders

### ISSUE THREAD

**Issue by LuxerIThink** [Tamaized/AlbedoTorches#1]
Could you make a support for shaders?, because shaders with this mod is glitched. There are two problems, first - The colors from this mod aren't visible and second the models from minecraft are glitched.
Screenshot without shaders:
https://imgur.com/a/RVv5e
Screenshots with shaders:
https://imgur.com/a/yu4gm
https://imgur.com/a/vEyN8
Thanks for help :)

**Comment by Tamaized** [comment]
This is an issue with Albedo itself.
