### ISSUE TITLE
Colored Torches do not change light level in debug screen.

### ISSUE THREAD

**Issue by kb5vei** [Tamaized/AlbedoTorches#2]
While the light from colored torches seems to prevent mobs from spawning (in my limited testing), the debug screen still says the light level is zero.

Currently using Minecraft 1.12.2, forge 14.23.1.2559

Steps to Reproduce:
1) Find a Dark place
2) Place a colored torch.
3) Press F3.

Expected Result:
Light level displayed is non-zero.

Actual Result: Light Level is zero.  
See screenshot:
![screenshot from 2018-01-04 07-21-04](https://user-images.githubusercontent.com/8752763/34567644-4a2cac64-f120-11e7-88f3-82b703357b18.png)

**Comment by Tamaized** [comment]
This is because the client side doesn't have the light level set, else you'd get the vanilla light and it'd break the color all together. Nothing I can do about this.
